Exercise 1
==========

Problem
-------

An Austin real-estate developer is interested in the possible economic
impact of "going green" in her latest project: a new <b> 15-story </b>
(height) <u>mixed-use </u> (not all green, nor all non-green) building
on <b> East Cesar Chavez </b> (location), just across I-35 from
downtown. <b> 250,000 square feet </b> (size) <b> expected baseline
construction costs are $100 million </b> (different types of rental
rate) <b> earning rents for 30 years or more </b> (possible building
age)

Question 1
==========

I do not agree with the analysis given. If we look at the distribution
of rent according to the size of the properties, we observe that the
median rate may not vary that much. However, if we seperate the rent
based on the type of contract, either gross contract or net contract,
there will be discrepancies across median rental rate based on property
size. I will classify the size of property based on four quartiles based
on the collecting data.

    ##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##    1624   50891  128838  234638  294212 3781045

![](Homework1_files/figure-markdown_strict/unnamed-chunk-2-1.png)

As you can observe from the box plot, the medians rental rate between
green versus non-green property for large properties
128838 &lt; *x* &lt; 294212 *f**e**e**t*<sup>2</sup> do not differ much
in net contracts but vary greatly in gross contracts, with green
building enjoys around $3.20. Hence, the rough estimate of difference in
rental rate between green and non-green building is questionable.

The next questionable assumption is the rent will be constant throughout
the life of the building. I will look into the median rent for an
interval of every 10 years

![](Homework1_files/figure-markdown_strict/unnamed-chunk-3-1.png)

Hence, forecasting the rent to stay constant throughout building's
lifetime is irrelevant. Therefore, the revenue stream will not be
constant, making the profit prediction after cost repcuperation is
dubious.
